### PR TITLE
Fix compilation error in ROS 2 gem

### PR DESCRIPTION
**Pull request by michalpelka**
## What does this PR do?

Fix compilation issue introduced in #944 

## How was this PR tested?

image

### CODE REVIEW

**Review by norbertprokopiuk — APPROVED** [review]
Looks good, changes fixes compilation

**Review by jhanca-robotecai — APPROVED** [review]
