### ISSUE TITLE
ROS2 Gem does not build with the newest Jazzy

### ISSUE THREAD

**Issue by jhanca-robotecai** [o3de/o3de-extras#813]
**Describe the bug**
`ROS 2 Gem` does not build on Ubuntu 24.04 with the newest _ROS 2 Jazzy_

**Steps to reproduce**
1. Update ROS 2 Jazzy to the newest version
2. Pull the code
3. Build

**Expected behavior**
The code builds

**Actual behavior**
```
In file included from /home/jhanca/devroot/2409/o3de-extras/Gems/ROS2/Code/Include/ROS2/Utilities/Controllers/PidConfiguration.h:11:
In file included from /opt/ros/jazzy/include/control_toolbox/control_toolbox/pid.hpp:41:
/opt/ros/jazzy/include/realtime_tools/realtime_tools/realtime_buffer.h:25:2: error: "This header include is deprecated. Please update your code to use 'realtime_buffer.hpp' header." //NOLINT [-Werror,-W#warnings]
   25 | #warning \
      |  ^
1 error generated.

```

**Found in Branch**
`main` (2409.1), but it will be the same in `development`

**Desktop/Device (please complete the following information):**
 - Device: Laptop
 - OS: Ubuntu 
 - Version 24.04.1. LTS
 
**Additional context**
Update that cause the issue:
```
Preparing to unpack .../151-ros-jazzy-control-toolbox_3.4.0-1noble.20241228.012401_amd64.deb ...
Unpacking ros-jazzy-control-toolbox (3.4.0-1noble.20241228.012401) over (3.3.0-1noble.20241118.192236)
```

**Comment by jhanca-robotecai** [comment]
The issue was auto-detected two weeks ago and raised on the respective repository: https://github.com/ros-controls/control_toolbox/issues/248

**Comment by adamdbrw** [comment]
This is the second time the control_toolbox package causes issues. The issue you point to has been closed as completed, could you check if this still a problem?
